; Classroom Noise Indicator - ESP32-S3 - v1
; Proyecto PlatformIO para Visual Studio Code

[env:esp32-s3-devkitc-1]
platform = espressif32@6.8.1
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Si tu placa ESP32-S3 no es exactamente DevKitC-1, puedes cambiar la línea "board" en PlatformIO.
; Ejemplos habituales: esp32-s3-devkitc-1, esp32-s3-devkitm-1, lolin_s3, esp32-s3-devkitc-1-n16r8.

lib_deps =
    madhephaestus/ESP32Servo@^1.2.1
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit NeoPixel@^1.12.3

build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
